# You can sponsor

github: [haybnzz] # GitHub Sponsors-enabled username for https://github.com/haybnzz/HadesConnect
patreon: https://www.patreon.com/c/Fluromide
liberapay: https://liberapay.com/Floraminde/
custom: https://haybnz.glitch.me/ # Custom Monero donation link and address
